/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Affichage_edt.java
 *
 * Created on 26 mars 2012, 15:47:56
 */
package edt.view;

import edt.Classe.Cours;
import edt.Classe.UE;
import edt.mysql.BD_MySQL;
import java.awt.Graphics;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Marie
 */
public class Affichage_edt extends javax.swing.JPanel {

    /** Creates new form Affichage_edt */
    private ArrayList<Cours> liste_Cours_promotion = new ArrayList();
    private ArrayList<Affichage_cours> liste_Cours ;
    public Affichage_edt() {
        initComponents();
        /*try {
            this.liste_Cours_promotion = BD_MySQL.liste_Cours_promotion(0);
        } catch (SQLException ex) {
            Logger.getLogger(Affichage_edt.class.getName()).log(Level.SEVERE, null, ex);
        }*/
       // AjoutCour();
    }
    public Affichage_edt(int idPromotion) {
        initComponents();
        try {
            this.liste_Cours_promotion = BD_MySQL.liste_Cours_promotion(idPromotion);
        } catch (SQLException ex) {
            Logger.getLogger(Affichage_edt.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void AjoutCour(){
        String nom = "";
        for (Cours l : this.liste_Cours_promotion) {
            try {
                nom = UE.nomUE(l.getIdUE());
            } catch (SQLException ex) {
                Logger.getLogger(Affichage_edt.class.getName()).log(Level.SEVERE, null, ex);
            }
            System.out.println(nom +" "+"cours"+" "+l.getTsDebut().getHours()*10+" "+l.getTsFin().getDate()*30);
           Affichage_cours cr =  new Affichage_cours(nom,"cours",l.getTsDebut().getHours()*10,l.getTsFin().getDay()*30+(l.getTsFin().getDate()/6)*160/*+l.getTsFin().getMonth()*500*/);
           this.add(cr);
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setName("Form"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 848, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
