/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edt.view;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author Marie
 */
public class Affichage_cours extends javax.swing.JPanel {
    
    private Color macouleur = Color.BLACK;
    private int PositionX;
    private int PositionY;
    /**
     * Creates new form Affichage_cours
     */
    public Affichage_cours() {
        initComponents();
        this.setSize(80, 25);
    }
    
    public Affichage_cours(String nom, String type, int X, int Y) {
        initComponents();
        this.setSize(80, 25);
        this.setLocation(Y, Y);
        this.cours.setText(nom);
        this.type.setText(type);
    }
    
    @Override
    public void paint(Graphics g) {
        super.paint(g);
        g.drawRect(0, 0, 80, 25);
    }
    
    public void setMacouleur(Color macouleur) {
        this.macouleur = macouleur;
        this.repaint();
    }
    public void setcour(String cour){
        this.cours.setText(cour);
    }
    public void settype(String type){
        this.type.setText("-"+type);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cours = new javax.swing.JLabel();
        type = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(100, 100));

        cours.setText("DCLL");

        type.setText("TP");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cours)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(type)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cours)
                    .addComponent(type))
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cours;
    private javax.swing.JLabel type;
    // End of variables declaration//GEN-END:variables
}
