/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Affichage_Cour.java
 *
 * Created on 26 mars 2012, 16:12:27
 */
package edt.view;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author Marie
 */
public class Affichage_Cour extends javax.swing.JPanel {
    private Color macouleur = Color.BLACK;
    /** Creates new form Affichage_Cour */
    public Affichage_Cour() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @Override
    public void paint(Graphics g) {
        super.paint(g);
        g.drawRect(0, 0, this.getWidth(), this.getHeight());
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cour = new java.awt.Label();
        type = new java.awt.Label();

        setName("Form"); // NOI18N

        cour.setName("cour"); // NOI18N
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(edt.EDTApp.class).getContext().getResourceMap(Affichage_Cour.class);
        cour.setText(resourceMap.getString("cour.text")); // NOI18N

        type.setName("type"); // NOI18N
        type.setText(resourceMap.getString("type.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label cour;
    private java.awt.Label type;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the macouleur
     */
    public Color getMacouleur() {
        return macouleur;
    }

    /**
     * @param macouleur the macouleur to set
     */
    public void setMacouleur(Color macouleur) {
        this.macouleur = macouleur;
        this.repaint();
    }
    public void setcour(String cour){
        this.cour.setText(cour);
    }
    public void settype(String type){
        this.type.setText("-"+type);
    }
}
