/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Affichage_edt.java
 *
 * Created on 26 mars 2012, 15:47:56
 */
package edt.view;

import edt.Classe.Cours;
import edt.Classe.EmploiDuTemps;
import edt.Classe.UE;
import edt.mysql.BD_MySQL;
import java.awt.Graphics;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JEditorPane;

/**
 *
 * @author Marie
 */
public class Affichage_edt extends javax.swing.JPanel {

    /** Creates new form Affichage_edt */
    public Affichage_edt() {
        initComponents();
        this.afficher_emploiDuTemps(4);
    }
    
    public Affichage_edt(int idPromotion) {
        initComponents();
        this.afficher_emploiDuTemps(idPromotion);
    }
    
    public final void afficher_emploiDuTemps(int idPromotion) {
       
        DateFormat formatter = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        long timeDebut = 0;
        /*
         * il faut récupérer la date d'heujourd'hui pour ensuite 
         * trouver le lundi et l'envoyer pour l'edt
         */
        try {
            timeDebut = formatter.parse("2012-02-06 00:00:00").getTime();
        } catch (ParseException ex) {
            Logger.getLogger(Affichage_edt.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            // La tu récupère le tableau HTML : A mettre dans le jMachin
            this.jEditorPane1.setContentType("text/html");
            this.jEditorPane1.setText(EmploiDuTemps.cours_semaine_promotion_html(idPromotion, new Timestamp(timeDebut)));
        } catch (SQLException ex) {
            Logger.getLogger(Affichage_edt.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void AjoutCour(){
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        semaine = new javax.swing.JLabel();
        prec = new javax.swing.JButton();
        suiv = new javax.swing.JButton();
        edt = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();

        setName("Form"); // NOI18N

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("edt/view/Bundle"); // NOI18N
        semaine.setText(bundle.getString("Affichage_edt.semaine.text")); // NOI18N
        semaine.setName(bundle.getString("Affichage_edt.semaine.name")); // NOI18N

        prec.setText(bundle.getString("Affichage_edt.prec.text")); // NOI18N
        prec.setName(bundle.getString("Affichage_edt.prec.name")); // NOI18N

        suiv.setText(bundle.getString("Affichage_edt.suiv.text")); // NOI18N
        suiv.setName(bundle.getString("Affichage_edt.suiv.name")); // NOI18N

        edt.setText(bundle.getString("Affichage_edt.edt.text")); // NOI18N
        edt.setName(bundle.getString("Affichage_edt.edt.name")); // NOI18N

        jScrollPane1.setName(bundle.getString("Affichage_edt.jScrollPane1.name")); // NOI18N

        jEditorPane1.setName(bundle.getString("Affichage_edt.jEditorPane1.name")); // NOI18N
        jScrollPane1.setViewportView(jEditorPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1094, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edt))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(380, 380, 380)
                        .addComponent(prec)
                        .addGap(266, 266, 266)
                        .addComponent(suiv))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(529, 529, 529)
                        .addComponent(semaine)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(semaine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(suiv, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(prec))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(edt))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel edt;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton prec;
    private javax.swing.JLabel semaine;
    private javax.swing.JButton suiv;
    // End of variables declaration//GEN-END:variables
}
