/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Donner.java
 *
 * Created on 26 mars 2012, 00:28:50
 */
package edt.view;

import com.sun.java.swing.plaf.windows.resources.windows;
import edt.mysql.BD_MySQL;
import edt.Classe.Etudiant;
import edt.Classe.Promotion;
import edt.Classe.UE;
import edt.Frame.Ajouter_Intervenant;
import edt.Frame.Ajouter_Salle;
import edt.Frame.NewSalle;
import edt.Frame.New_Etudiant;
import edt.Frame.New_UE;
import java.awt.Frame;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marie
 */
public class Donner extends javax.swing.JPanel {
    private New_UE ued;
    private Ajouter_Intervenant inter;
    private NewSalle salle;
    private New_Etudiant etud;
    private long id;
    private ArrayList<Etudiant> list_etu;
    private ArrayList<UE> list_ue;
    /** Creates new form Donner */
    public Donner() {
        initComponents();
        this.id = 0;
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titre = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        modifier = new javax.swing.JButton();
        supprimer = new javax.swing.JButton();
        ajouter = new javax.swing.JButton();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(edt.EDTApp.class).getContext().getResourceMap(Donner.class);
        titre.setText(resourceMap.getString("titre.text")); // NOI18N
        titre.setName("titre"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        
        jTable1.setName("jTable1"); // NOI18N
		jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        modifier.setText(resourceMap.getString("modifier.text")); // NOI18N
        modifier.setName("modifier"); // NOI18N
        modifier.setEnabled(false);
		modifier.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierActionPerformed(evt);
            }
        });

        supprimer.setText(resourceMap.getString("supprimer.text")); // NOI18N
        supprimer.setName("supprimer"); // NOI18N
        supprimer.setEnabled(false);
		supprimer.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerActionPerformed(evt);
            }
        });

        ajouter.setText(resourceMap.getString("ajouter.text")); // NOI18N
        ajouter.setName("ajouter"); // NOI18N
		ajouter.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(titre))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(126, 126, 126)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ajouter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(supprimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(modifier, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                .addContainerGap(193, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titre)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(modifier)
                        .addGap(18, 18, 18)
                        .addComponent(supprimer)
                        .addGap(18, 18, 18)
                        .addComponent(ajouter))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouter;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton modifier;
    private javax.swing.JButton supprimer;
    private javax.swing.JLabel titre;
    // End of variables declaration//GEN-END:variables
	
 private void modifierActionPerformed(java.awt.event.ActionEvent evt) { 
        switch(etat){
            case UE:
                //interdit
                break;
            case UE1:
                ued = new New_UE(new java.awt.Frame(),"Ajouter une UE",true,this,"UE1",id);
                ued.setVisible(true);
                etat = Etat.UE;
                break;
            case Intervenant:
                inter = new Ajouter_Intervenant();
                inter.setVisible(true);
                etat = Etat.Intervenant;
                break;
            case Salle:
                //interdit
                break;
            case Salle1:
                salle = new NewSalle(new java.awt.Frame(),"Ajouter une Salle",true,this,"Salle1",id);
                salle.setVisible(true);
                etat = Etat.Salle;
                break;
            case Etudiant:
                //interdit
                break;
            case Etudiant1:
                etud = new New_Etudiant(new java.awt.Frame(),"Ajouter un Etudiant",true,this,"Etudiant1",id);
                etud.setVisible(true);
                etat = Etat.Etudiant;
                break;
        }
 }
 
 private void supprimerActionPerformed(java.awt.event.ActionEvent evt) { 
        switch(etat){
            case UE:
                //interdit
                break;
            case UE1:
                ued = new New_UE(new java.awt.Frame(),"Ajouter une UE",true);
                ued.setVisible(true);
                etat = Etat.UE;
                break;
            case Intervenant:
                inter = new Ajouter_Intervenant();
                inter.setVisible(true);
                etat = Etat.Intervenant;
                break;
            case Salle:
                salle = new NewSalle(new java.awt.Frame(),"Ajouter une Salle",true,this,"Salle",0);
                salle.setVisible(true);
                etat = Etat.Salle;
                break;
            case Etudiant:
                //interdit
                break;
            case Etudiant1:
                Etudiant etu = null;
                try {
                   etu = new Etudiant(4);
                } catch (SQLException ex) {
                    Logger.getLogger(Donner.class.getName()).log(Level.SEVERE, null, ex);
                }
                etu.delete();
                etat = Etat.Etudiant;
                
                break;
        }
 }
 private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
        switch(etat){
            case UE:
                ued = new New_UE(new java.awt.Frame(),"Ajouter une UE",true,this,"UE",0);
                ued.setVisible(true);
                etat = Etat.UE;
                break;
            case UE1:
                ued = new New_UE(new java.awt.Frame(),"Ajouter une UE",true,this,"UE",0);
                ued.setVisible(true);
                etat = Etat.UE;
                break;
            case Intervenant:
                inter = new Ajouter_Intervenant();
                inter.setVisible(true);
                etat = Etat.Intervenant;
                break;
            case Salle:
                salle = new NewSalle(new java.awt.Frame(),"Ajouter une Salle",true,this,"Salle",0);
                salle.setVisible(true);
                etat = Etat.Salle;
                break;
            case Salle1:
                salle = new NewSalle(new java.awt.Frame(),"Ajouter une Salle",true,this,"Salle",0);
                salle.setVisible(true);
                etat = Etat.Salle;
                break;
            case Etudiant:
                etud = new New_Etudiant(new java.awt.Frame(),"Ajouter un Etudiant",true,this,"Etudiant",0);
                etud.setVisible(true);
                etat = Etat.Etudiant;
                break;
            case Etudiant1:
                etud = new New_Etudiant(new java.awt.Frame(),"Ajouter un Etudiant",true,this,"Etudiant",0);
                etud.setVisible(true);
                etat = Etat.Etudiant;
                break;
        }
    } 
   public void active_sup_modif(){
       this.supprimer.setEnabled(true);
       this.modifier.setEnabled(true);
   }
    public void desactive_sup_modif(){
       this.supprimer.setEnabled(false);
       this.modifier.setEnabled(false);
   }
   
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        int ligne = jTable1.getSelectedRow();
        int colonne = jTable1.getSelectedColumn();
	switch(etat){
            case UE:
                id = id_UE();
                active_sup_modif();
                etat = Etat.UE1;
                break;
            case UE1:
                id = id_UE();
                active_sup_modif();
                etat = Etat.UE1;
                break;
            case Intervenant:
                active_sup_modif();
                
                break;
            case Salle:
                active_sup_modif();
                
                break;
                
            case Salle1:
                active_sup_modif();
                
                break;
            case Etudiant:
                id = id_Etudiant();
                active_sup_modif();
                etat = Etat.Etudiant1;
                break;
            case Etudiant1:
                id = id_Etudiant();
                active_sup_modif();
                etat = Etat.Etudiant1;
                break;
        }
    }
 public ArrayList<String> list_nom_UE(ArrayList<UE> liste_ue){
     ArrayList<String> liste_UE_promotion = new ArrayList();
     for (UE l : liste_ue) {
            liste_UE_promotion.add(l.getNom());
        }
     return liste_UE_promotion;
}
 public ArrayList<String> list_intitule_UE(ArrayList<UE> liste_ue){
     ArrayList<String> liste_UE_promotion = new ArrayList();
     for (UE l : liste_ue) {
            liste_UE_promotion.add(l.getIntitule());
        }
     return liste_UE_promotion;
}
 
 public ArrayList<Integer> list_nbcour_UE(ArrayList<UE> liste_ue){
     ArrayList<Integer> liste_UE_promotion = new ArrayList();
     for (UE l : liste_ue) {
            liste_UE_promotion.add(l.getNbHeuresCours());
        }
     return liste_UE_promotion;
}
 public ArrayList<Integer> list_nbtp_UE(ArrayList<UE> liste_ue){
     ArrayList<Integer> liste_UE_promotion = new ArrayList();
     for (UE l : liste_ue) {
            liste_UE_promotion.add(l.getNbHeuresTP());
        }
     return liste_UE_promotion;
}
  public ArrayList<Integer> list_nbtd_UE(ArrayList<UE> liste_ue){
     ArrayList<Integer> liste_UE_promotion = new ArrayList();
     for (UE l : liste_ue) {
            liste_UE_promotion.add(l.getNbHeuresTD());
        }
     return liste_UE_promotion;
}
  public void refreshUE(){
      System.out.println("coucouocu");
    this.jTable1.doLayout();
    DefaultTableModel modell = new DefaultTableModel(
            new Object [4][5] ,
            new String [] {});	
    jTable1.setModel(modell);
    try {
        this.list_ue = BD_MySQL.liste_UE_promotion(4);
    } catch (SQLException ex) {
        Logger.getLogger(Donner.class.getName()).log(Level.SEVERE, null, ex);
    }
    ArrayList<String> listenom = list_nom_UE(this.list_ue); 
    modell.addColumn("Nom", listenom.toArray()); 
    ArrayList<String> listeintitule = list_intitule_UE(this.list_ue); 
    modell.addColumn("Intitule", listeintitule.toArray()); 
    ArrayList<Integer> listenbCour = list_nbcour_UE(this.list_ue); 
    modell.addColumn("NB Heure Cours", listenbCour.toArray()); 
    ArrayList<Integer> listenbTP = list_nbtp_UE(this.list_ue); 
    modell.addColumn("NB Heure TP", listenbTP.toArray()); 
    ArrayList<Integer> listenbTD = list_nbtd_UE(this.list_ue); 
    modell.addColumn("NB Heure TD", listenbTD.toArray()); 
  }
    public void frame_UE(){
    this.titre.setText("UE");
    this.ajouter.setText("Ajouter une UE");
    refreshUE();
}

public void frame_Intervenant(){
    this.titre.setText("Intervenant");
    this.ajouter.setText("Ajouter un Intervenant");
    jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nom", "Capacité", 
            }
        ));
}
public ArrayList<String> list_nom_etudiant(ArrayList<Etudiant> liste_etu){
     ArrayList<String> liste_etudiants_promotion = new ArrayList();
     for (Etudiant l : liste_etu) {
            liste_etudiants_promotion.add(l.getNom());
        }
     return liste_etudiants_promotion;
}
public ArrayList<String> list_prenom_etudiant(ArrayList<Etudiant> liste_etu){
     ArrayList<String> liste_etudiants_promotion = new ArrayList();
     for (Etudiant l : liste_etu) {
            liste_etudiants_promotion.add(l.getPrenom());
        }
     return liste_etudiants_promotion;
}
public ArrayList<Integer> list_NEtudiant_etudiant(ArrayList<Etudiant> liste_etu){
     ArrayList<Integer> liste_etudiants_promotion = new ArrayList();
     for (Etudiant l : liste_etu) {
            liste_etudiants_promotion.add(l.getNumeroEtudiant());
        }
     return liste_etudiants_promotion;
}
public ArrayList<String> list_telephone_etudiant(ArrayList<Etudiant> liste_etu){
     ArrayList<String> liste_etudiants_promotion = new ArrayList();
     for (Etudiant l : liste_etu) {
            liste_etudiants_promotion.add(l.getTelephone());
        }
     return liste_etudiants_promotion;
}
public ArrayList<String> list_email_etudiant(ArrayList<Etudiant> liste_etu){
     ArrayList<String> liste_etudiants_promotion = new ArrayList();
     for (Etudiant l : liste_etu) {
            liste_etudiants_promotion.add(l.getEmail());
        }
     return liste_etudiants_promotion;
}
public void frame_Etudiant() throws SQLException {
    this.titre.setText("Etudiant");
    this.ajouter.setText("Ajouter un Etudiant");
    refresh();
}
public void refresh() throws SQLException{
    this.jTable1.doLayout();
    DefaultTableModel modell = new DefaultTableModel(
            new Object [4][5] ,
            new String [] {});	
    jTable1.setModel(modell);
    this.list_etu = BD_MySQL.liste_etudiants_promotion(4);
    ArrayList<String> listenom = list_nom_etudiant(this.list_etu); 
    modell.addColumn("Nom", listenom.toArray()); 
    ArrayList<String> listeprenom = list_prenom_etudiant(this.list_etu); 
    modell.addColumn("Prénom", listeprenom.toArray()); 
    ArrayList<Integer> listeNEtudiant = list_NEtudiant_etudiant(this.list_etu); 
    modell.addColumn("N°Etudiant", listeNEtudiant.toArray()); 
    ArrayList<String> listeTelephone = list_telephone_etudiant(this.list_etu); 
    modell.addColumn("Téléphone", listeTelephone.toArray()); 
    ArrayList<String> listeEmail = list_email_etudiant(this.list_etu); 
    modell.addColumn("Email", listeEmail.toArray());
    
}
public void frame_Salle(){
    this.titre.setText("Salle");
    this.ajouter.setText("Ajouter une Salle");
    jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nom", "Capacité", 
            }
        ));
    
}

    private long id_Etudiant() {
        long id = 0;
        int ligne = jTable1.getSelectedRow();
        int netudiant = Integer.parseInt((jTable1.getValueAt(ligne,2)).toString());
        String nom = (jTable1.getValueAt(ligne,0)).toString();
        String prenom = (jTable1.getValueAt(ligne,1)).toString();
        try {
            id = BD_MySQL.id_etudiants_promotion(netudiant,nom,prenom,4);
        } catch (SQLException ex) {
            Logger.getLogger(Donner.class.getName()).log(Level.SEVERE, null, ex);
        }
        return id;
    }
private long id_UE() {
        long id = 0;
        int ligne = jTable1.getSelectedRow();
        String nom = (jTable1.getValueAt(ligne,0)).toString();
        try {
            id = BD_MySQL.id_UE_promotion(nom,4);
        } catch (SQLException ex) {
            Logger.getLogger(Donner.class.getName()).log(Level.SEVERE, null, ex);
        }
        return id;
    }
    
 private enum Etat{
        UE,
        UE1,
        Salle,
        Salle1,
        Etudiant,
        Etudiant1,
        Intervenant
            
                
    }
    private Etat etat;
    public void setEtat(String n){
        if(n.equals("UE"))
            etat = Etat.UE;
        else if(n.equals("Salle"))
            etat = Etat.Salle;
        else if(n.equals("Intervenant"))
            etat = Etat.Intervenant;
        else if(n.equals("Etudiant"))
            etat = Etat.Etudiant;
    }
}
