/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Donner.java
 *
 * Created on 26 mars 2012, 00:28:50
 */
package edt.view;

import com.sun.java.swing.plaf.windows.resources.windows;
import edt.mysql.BD_MySQL;
import edt.Classe.Etudiant;
import edt.Frame.Ajouter_Intervenant;
import edt.Frame.Ajouter_Salle;
import edt.Frame.New_Etudiant;
import edt.Frame.New_UE;
import java.awt.Frame;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marie
 */
public class Donner extends javax.swing.JPanel {
    private New_UE ued;
    private Ajouter_Intervenant inter;
    private Ajouter_Salle salle;
    private New_Etudiant etud;
    /** Creates new form Donner */
    public Donner() {
        initComponents();
        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titre = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        modifier = new javax.swing.JButton();
        supprimer = new javax.swing.JButton();
        ajouter = new javax.swing.JButton();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(edt.EDTApp.class).getContext().getResourceMap(Donner.class);
        titre.setText(resourceMap.getString("titre.text")); // NOI18N
        titre.setName("titre"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        
        jTable1.setName("jTable1"); // NOI18N
        jScrollPane1.setViewportView(jTable1);

        modifier.setText(resourceMap.getString("modifier.text")); // NOI18N
        modifier.setName("modifier"); // NOI18N
        modifier.setEnabled(false);

        supprimer.setText(resourceMap.getString("supprimer.text")); // NOI18N
        supprimer.setName("supprimer"); // NOI18N
        supprimer.setEnabled(false);

        ajouter.setText(resourceMap.getString("ajouter.text")); // NOI18N
        ajouter.setName("ajouter"); // NOI18N
		ajouter.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(titre))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(126, 126, 126)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ajouter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(supprimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(modifier, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                .addContainerGap(193, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titre)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(modifier)
                        .addGap(18, 18, 18)
                        .addComponent(supprimer)
                        .addGap(18, 18, 18)
                        .addComponent(ajouter))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouter;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton modifier;
    private javax.swing.JButton supprimer;
    private javax.swing.JLabel titre;
    // End of variables declaration//GEN-END:variables
 private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
        switch(etat){
            case UE:
                ued = new New_UE(new java.awt.Frame(),"Ajouter une UE",true);
                
                ued.setVisible(true);
                etat = etat.UE;
                break;
            case Intervenant:
                inter = new Ajouter_Intervenant();
                inter.setVisible(true);
                etat = etat.Intervenant;
                break;
            case Salle:
                salle = new Ajouter_Salle();
                salle.setVisible(true);
                etat = etat.Salle;
                break;
            case Etudiant:
                etud = new New_Etudiant(new java.awt.Frame(),"Ajouter un Etudiant",true);
                
                etud.setVisible(true);
                etat = etat.Etudiant;
                break;
        }
    } 
    
    public void frame_UE(){
    this.titre.setText("UE");
    this.ajouter.setText("Ajouter une UE");
    jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            
            new String [] {
                "Nom", "Nb heure Cours", "Nb heure TP", "Nb heure TD"
            }
        ));
    
}
public void frame_Intervenant(){
    this.titre.setText("Intervenant");
    this.ajouter.setText("Ajouter un Intervenant");
    jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nom", "Prenom", 
            }
        ));
    
}
public String prenom_bis() throws SQLException{

            ArrayList<Etudiant> list = BD_MySQL.liste_etudiants_promotion(4);
            System.out.println(list.get(1).getPrenom());
            return list.get(1).getPrenom();
}
public void frame_Etudiant() throws SQLException {
    this.titre.setText("Etudiant");
    this.ajouter.setText("Ajouter un Etudiant");
    DefaultTableModel modell = new DefaultTableModel(
            new Object [4][5] ,
            new String [] {});	
    jTable1.setModel(modell);
    List listenom = BD_MySQL.liste_nom_etudiants_promotion(4); 
    modell.addColumn("Nom", listenom.toArray()); 
    List listeprenom = BD_MySQL.liste_prenom_etudiants_promotion(4); 
    modell.addColumn("Prénom", listeprenom.toArray()); 
}
public void refresh() throws SQLException{
    this.jTable1.doLayout();
    DefaultTableModel modell = new DefaultTableModel(
            new Object [4][5] ,
            new String [] {});	
    jTable1.setModel(modell);
    List listenom = BD_MySQL.liste_nom_etudiants_promotion(4); 
    modell.addColumn("Nom", listenom.toArray()); 
    List listeprenom = BD_MySQL.liste_prenom_etudiants_promotion(4); 
    modell.addColumn("Prénom", listeprenom.toArray()); 
    
}
public void frame_Salle(){
    this.titre.setText("Salle");
    this.ajouter.setText("Ajouter une Salle");
    jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nom", "Capacité", 
            }
        ));
    
}

    
 private enum Etat{
        UE,
        Salle,
        Etudiant,
        Intervenant
            
                
    }
    private Etat etat;
    public void setEtat(String n){
        if(n.equals("UE"))
            etat = etat.UE;
        else if(n.equals("Salle"))
            etat = etat.Salle;
        else if(n.equals("Intervenant"))
            etat = etat.Intervenant;
        else if(n.equals("Etudiant"))
            etat = etat.Etudiant;
    }
}
