/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * New_UE.java
 *
 * Created on 30 mars 2012, 14:35:37
 */
package edt.Frame;
import edt.Classe.UE;
import edt.mysql.BD_MySQL;
import edt.view.Donner;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Marie
 */
public class New_UE extends javax.swing.JDialog {
    private Donner donner;
    private long id;
    private UE ue;
    /** Creates new form New_UE */
    public New_UE(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public New_UE(java.awt.Frame parent, String titre,boolean modal) {
        super(parent, titre,modal);
        initComponents();
        this.setLocation( Toolkit.getDefaultToolkit().getScreenSize().width/2-this.getWidth()/2,Toolkit.getDefaultToolkit().getScreenSize().height/2-this.getHeight()/2);
    
    }
    public New_UE(java.awt.Frame parent,String titre, boolean modal,Donner donner, String etat, long id) {
        super(parent,titre, modal);
        initComponents();
        init(etat,id);
        this.donner = donner;
        this.setLocation( Toolkit.getDefaultToolkit().getScreenSize().width/2-this.getWidth()/2,Toolkit.getDefaultToolkit().getScreenSize().height/2-this.getHeight()/2);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        nb_cour = new javax.swing.JTextField();
        nb_tp = new javax.swing.JTextField();
        nb_td = new javax.swing.JTextField();
        valider = new javax.swing.JButton();
        annuler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nom");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText("Nb Heure Cours");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText("Nb Heure TP");
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText("Nb Heure TD");
        jLabel4.setName("jLabel4"); // NOI18N

        nom.setName("nom"); // NOI18N

        nb_cour.setName("nb_cour"); // NOI18N

        nb_tp.setName("nb_tp"); // NOI18N

        nb_td.setName("nb_td"); // NOI18N

        valider.setText("Valider");
        valider.setName("valider"); // NOI18N
        valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerActionPerformed(evt);
            }
        });

        annuler.setText("Annuler");
        annuler.setName("annuler"); // NOI18N
        annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(nb_cour, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                        .addComponent(nb_tp, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                        .addComponent(nb_td, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(annuler)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valider)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nb_cour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nb_tp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nb_td, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valider)
                    .addComponent(annuler))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void refresh(){
    this.nom.setText("");
    this.nb_cour.setText("");
    this.nb_td.setText("");
    this.nb_tp.setText("");
    this.donner.desactive_sup_modif();
    this.ue = null;
  /*  try {
        this.donner.refresh();
     } catch (SQLException ex) {
         Logger.getLogger(New_Etudiant.class.getName()).log(Level.SEVERE, null, ex);
    }*/
}
private void creer(){
        this.ue.setNom(this.nom.getText());
        this.ue.setNbHeuresCours(Integer.parseInt(this.nb_cour.getText()));
        this.ue.setNbHeuresTD(Integer.parseInt(this.nb_td.getText()));
        this.ue.setNbHeuresTP(Integer.parseInt(this.nb_tp.getText()));
}
    private void validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerActionPerformed
        // TODO add your handling code here:
        BD_MySQL.init();
        switch(etat){
            case UE:
                this.ue = new UE(this.nom.getText(),"",Integer.parseInt(this.nb_cour.getText()),Integer.parseInt(this.nb_td.getText()),Integer.parseInt(this.nb_tp.getText()),3,4);
                this.ue.save();
                refresh();
                etat = Etat.UE;
                break;
            case UE1:
                creer();
                this.ue.save();
                refresh();
                this.dispose();
                break;
                
        }
    }//GEN-LAST:event_validerActionPerformed

    private void annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerActionPerformed
        // TODO add your handling code here:
        switch(etat){
            case UE:
                this.dispose();
                this.donner.desactive_sup_modif();
                break;
            case UE1:
                this.dispose();
                this.donner.desactive_sup_modif();
                break;
                
        }
    }//GEN-LAST:event_annulerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(New_UE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(New_UE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(New_UE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(New_UE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                New_UE dialog = new New_UE(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annuler;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nb_cour;
    private javax.swing.JTextField nb_td;
    private javax.swing.JTextField nb_tp;
    private javax.swing.JTextField nom;
    private javax.swing.JButton valider;
    // End of variables declaration//GEN-END:variables
    private enum Etat{
        UE,
        UE1    
    }
    private Etat etat;
    public void init(String n,long id){
        if(n.equals("UE"))
            etat = Etat.UE;
        else if (n.equals("UE1")){
            etat = Etat.UE;
            try {
                this.ue = new UE(id);
            } catch (SQLException ex) {
                Logger.getLogger(New_UE.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.nom.setText(this.ue.getNom());
            this.nb_cour.setText(String.valueOf(this.ue.getNbHeuresCours()));
            this.nb_td.setText(String.valueOf(this.ue.getNbHeuresTD()));
            this.nb_tp.setText(String.valueOf(this.ue.getNbHeuresTP()));
        }
    }
}
