/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * New_Etudiant.java
 *
 * Created on 30 mars 2012, 13:46:50
 */
package edt.Frame;

import edt.mysql.BD_MySQL;
import edt.Classe.Etudiant;
import edt.Classe.Specialite;
import edt.Classe.UE;
import edt.view.Donner;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author Marie
 */
public class New_Etudiant extends javax.swing.JDialog {
    private Donner donner;
    private int id_promo;
    private Etudiant etudiant;
       private DefaultListModel modell = new DefaultListModel();
       private DefaultListModel modellinscrit = new DefaultListModel();
    /** Creates new form New_Etudiant */
    public New_Etudiant(){
        super();
        initComponents();
        this.setLocation( Toolkit.getDefaultToolkit().getScreenSize().width/2-this.getWidth()/2,Toolkit.getDefaultToolkit().getScreenSize().height/2-this.getHeight()/2);
    }
    public New_Etudiant(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocation( Toolkit.getDefaultToolkit().getScreenSize().width/2-this.getWidth()/2,Toolkit.getDefaultToolkit().getScreenSize().height/2-this.getHeight()/2);
    }
    public New_Etudiant(java.awt.Frame parent,String titre, boolean modal) {
        super(parent,titre, modal);
        initComponents();
        this.setLocation( Toolkit.getDefaultToolkit().getScreenSize().width/2-this.getWidth()/2,Toolkit.getDefaultToolkit().getScreenSize().height/2-this.getHeight()/2);
    }
    public New_Etudiant(java.awt.Frame parent,String titre, boolean modal,Donner donner) {
        super(parent,titre, modal);
        initComponents();
        this.donner = donner;
        this.setLocation( Toolkit.getDefaultToolkit().getScreenSize().width/2-this.getWidth()/2,Toolkit.getDefaultToolkit().getScreenSize().height/2-this.getHeight()/2);
    }
    public New_Etudiant(java.awt.Frame parent,String titre, boolean modal,Donner donner, String etat, int id, int id_promo) {
        super(parent,titre, modal);
        initComponents();
        this.id_promo = id_promo;
        init(etat,id);
        this.donner = donner;
        this.setLocation( Toolkit.getDefaultToolkit().getScreenSize().width/2-this.getWidth()/2,Toolkit.getDefaultToolkit().getScreenSize().height/2-this.getHeight()/2);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        prenom = new javax.swing.JTextField();
        nEtudiant = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        telephone = new javax.swing.JTextField();
        specialite = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListUE = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListUEInscrit = new javax.swing.JList();
        jLabel7 = new javax.swing.JLabel();
        valider = new javax.swing.JButton();
        annuler = new javax.swing.JButton();
        inscrit = new javax.swing.JButton();
        ttinscrit = new javax.swing.JButton();
        desincrit = new javax.swing.JButton();
        ttdesinscrit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nom");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText("Prénom");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText("N° Etudiant");
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText("Email");
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setText("Téléphone");
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setText("Spécialité");
        jLabel6.setName("jLabel6"); // NOI18N

        nom.setName("nom"); // NOI18N

        prenom.setName("prenom"); // NOI18N

        nEtudiant.setName("nEtudiant"); // NOI18N

        email.setName("email"); // NOI18N

        telephone.setName("telephone"); // NOI18N

        specialite.setName("specialite"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jListUE.setName("jListUE"); // NOI18N
        jListUE.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jListUEAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jListUE);

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jListUEInscrit.setName("jListUEInscrit"); // NOI18N
        jListUEInscrit.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jListUEInscritAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane2.setViewportView(jListUEInscrit);

        jLabel7.setText("UE");
        jLabel7.setName("jLabel7"); // NOI18N

        valider.setText("Valider");
        valider.setName("valider"); // NOI18N
        valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerActionPerformed(evt);
            }
        });

        annuler.setText("Annuler");
        annuler.setName("annuler"); // NOI18N
        annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerActionPerformed(evt);
            }
        });

        inscrit.setText(">");
        inscrit.setName("inscrit"); // NOI18N
        inscrit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inscritActionPerformed(evt);
            }
        });

        ttinscrit.setText(">>");
        ttinscrit.setName("ttinscrit"); // NOI18N
        ttinscrit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttinscritActionPerformed(evt);
            }
        });

        desincrit.setText("<");
        desincrit.setName("desincrit"); // NOI18N
        desincrit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desincritActionPerformed(evt);
            }
        });

        ttdesinscrit.setText("<<");
        ttdesinscrit.setName("ttdesinscrit"); // NOI18N
        ttdesinscrit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttdesinscritActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(inscrit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ttinscrit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ttdesinscrit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(desincrit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(specialite, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nEtudiant)
                            .addComponent(prenom)
                            .addComponent(nom, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                            .addComponent(telephone, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                            .addComponent(email))))
                .addGap(91, 91, 91))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(annuler)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(valider)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nEtudiant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(telephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(specialite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(inscrit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ttinscrit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(desincrit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ttdesinscrit)))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valider)
                    .addComponent(annuler))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void refresh(){
    this.prenom.setText("");
    this.nom.setText("");
    this.email.setText("");
    this.nEtudiant.setText("");
    this.telephone.setText("");
    this.donner.desactive_sup_modif();
    this.etudiant = null;
    this.donner.refreshEtudiant();
}
private void creer(){
        this.etudiant.setNom(this.nom.getText());
        this.etudiant.setPrenom(this.prenom.getText());
        this.etudiant.setTelephone(this.telephone.getText());
        this.etudiant.setEmail(this.email.getText());
}
/*
 * A ajouter:
 * lors de la validation l'inscription des UE doit se faire 
 * suivant la liste des UE sélectionné
 */
    private void validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerActionPerformed
        
        switch(etat){
            case Etudiant:
                this.etudiant = new Etudiant(Integer.parseInt(this.nEtudiant.getText())
                        ,this.prenom.getText(),this.nom.getText(),this.email.getText(),
                        this.telephone.getText(),true,this.id_promo,
                        Specialite.id_Specialite_promotion(this.specialite.getSelectedItem().toString(),this.id_promo));
                this.etudiant.save();
                refresh();
                etat = Etat.Etudiant;
                break;
            case Etudiant1:
                creer();
                this.etudiant.save();
                refresh();
                this.dispose();
                break;
                
        }
        
    }//GEN-LAST:event_validerActionPerformed

    private void annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerActionPerformed
        // TODO add your handling code here:
        switch(etat){
            case Etudiant:
                this.dispose();
                this.donner.desactive_sup_modif();
                break;
            case Etudiant1:
                this.dispose();
                this.donner.desactive_sup_modif();
                break;
                
        }
    }//GEN-LAST:event_annulerActionPerformed

    private void inscritActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inscritActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inscritActionPerformed

    private void ttinscritActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttinscritActionPerformed
        // TODO add your handling code here:
        this.jListUE.doLayout();
        modell.removeAllElements();
        this.jListUE.setModel(modell);
        
        refreshUEinscrit();
    }//GEN-LAST:event_ttinscritActionPerformed

    private void desincritActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desincritActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desincritActionPerformed

    private void ttdesinscritActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttdesinscritActionPerformed
        // TODO add your handling code here:
        this.jListUEInscrit.doLayout();
        modellinscrit.removeAllElements();
        this.jListUEInscrit.setModel(modellinscrit);
        this.refreshUE();
    }//GEN-LAST:event_ttdesinscritActionPerformed

    private void jListUEAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jListUEAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jListUEAncestorAdded

    private void jListUEInscritAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jListUEInscritAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jListUEInscritAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(New_Etudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(New_Etudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(New_Etudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(New_Etudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                New_Etudiant dialog = new New_Etudiant(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annuler;
    private javax.swing.JButton desincrit;
    private javax.swing.JTextField email;
    private javax.swing.JButton inscrit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList jListUE;
    private javax.swing.JList jListUEInscrit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nEtudiant;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField prenom;
    private javax.swing.JComboBox specialite;
    private javax.swing.JTextField telephone;
    private javax.swing.JButton ttdesinscrit;
    private javax.swing.JButton ttinscrit;
    private javax.swing.JButton valider;
    // End of variables declaration//GEN-END:variables

    private enum Etat{
        Etudiant,
        Etudiant1
    }
    private Etat etat;
    public void refreshUE(){
        this.jListUE.doLayout();
        this.jListUE.setModel(modell);
        ArrayList<String> listenom = new ArrayList();
        listenom = UE.list_nom_UE(this.id_promo);
        for (String l : listenom) {
            modell.addElement(l); 
        }
        
    }
    public void refreshUEinscrit(){
        this.jListUEInscrit.doLayout();
        this.jListUEInscrit.setModel(modellinscrit);
        ArrayList<String> listenom = new ArrayList();
        listenom = UE.list_nom_UE(this.id_promo);
        for (String l : listenom) {
            modellinscrit.addElement(l); 
        }
        
    }
    public void init(String n,int id){
        if(n.equals("Etudiant"))
            etat = Etat.Etudiant;
        else if (n.equals("Etudiant1")){
            etat = Etat.Etudiant1;
            try {
                this.etudiant = new Etudiant(id);
            } catch (SQLException ex) {
                Logger.getLogger(New_Etudiant.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.nom.setText(etudiant.getNom());
            this.prenom.setText(etudiant.getPrenom());
            this.email.setText(etudiant.getEmail());
            this.telephone.setText(etudiant.getTelephone());
            this.nEtudiant.setText(String.valueOf(etudiant.getNumeroEtudiant()));
        }
         for(String nomSpecialite : Specialite.list_nom_Specialite(this.id_promo)){
           this.specialite.addItem(nomSpecialite);
        }
        refreshUE();
    }
}
