/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * New_Intervenant.java
 *
 * Created on 6 avr. 2012, 00:10:18
 */
package edt.Frame;

import edt.Classe.Creneau_Intervenant;
import edt.Classe.Intervenant;
import edt.mysql.BD_MySQL;
import edt.view.Donner;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marie
 */
public class New_Intervenant extends javax.swing.JDialog {
    private Donner donner;
    private int id;
    private Intervenant intervenant;
    private Creneau_Intervenant creneauInt;
    private ArrayList<Creneau_Intervenant> list_creneauInter;
    /** Creates new form New_Intervenant */
    public New_Intervenant(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public New_Intervenant(java.awt.Frame parent,String titre, boolean modal,Donner donner, String etat, int id) {
        super(parent,titre, modal);
        initComponents();
        init(etat,id);
        this.donner = donner;
        this.setLocation( Toolkit.getDefaultToolkit().getScreenSize().width/2-this.getWidth()/2,Toolkit.getDefaultToolkit().getScreenSize().height/2-this.getHeight()/2);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        recurrence = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        prenom = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        periode = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        h_debut = new javax.swing.JComboBox();
        h_fin = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        m_debut = new javax.swing.JComboBox();
        m_fin = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        ajout_dispo = new javax.swing.JButton();
        valider = new javax.swing.JButton();
        annuler = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        telephone = new javax.swing.JTextField();

        jScrollPane1.setName("jScrollPane1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setName("jTable1");
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Nom");
        jLabel1.setName("jLabel1");

        jLabel2.setText("Prénom");
        jLabel2.setName("jLabel2");

        jLabel3.setText("Disponibilité");
        jLabel3.setName("jLabel3");

        jLabel4.setText("Date");
        jLabel4.setName("jLabel4");

        jLabel5.setText("Heure début");
        jLabel5.setName("jLabel5");

        jLabel6.setText("Heure fin");
        jLabel6.setName("jLabel6");

        jLabel7.setText("Récurrence");
        jLabel7.setName("jLabel7");

        recurrence.setText("récurrence");
        recurrence.setName("recurrence");

        jLabel8.setText("Période de ");
        jLabel8.setName("jLabel8");

        nom.setName("nom");

        prenom.setName("prenom");

        date.setText("jj/mm/aaaa");
        date.setName("date");

        periode.setName("periode");

        jLabel9.setText("semaine");
        jLabel9.setName("jLabel9");

        h_debut.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));
        h_debut.setName("h_debut");
        h_debut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h_debutActionPerformed(evt);
            }
        });

        h_fin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));
        h_fin.setName("h_fin");

        jLabel10.setText("h");
        jLabel10.setName("jLabel10");

        jLabel11.setText("h");
        jLabel11.setName("jLabel11");

        m_debut.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "15", "30", "45" }));
        m_debut.setName("m_debut");

        m_fin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "15", "30", "45" }));
        m_fin.setName("m_fin");

        jScrollPane2.setName("jScrollPane2");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Date", "Heure Début", "Heure Fin"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setName("jTable2");
        jScrollPane2.setViewportView(jTable2);

        ajout_dispo.setText("Ajouter une disponibilité");
        ajout_dispo.setName("ajout_dispo");
        ajout_dispo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajout_dispoActionPerformed(evt);
            }
        });

        valider.setText("Valider");
        valider.setName("valider");
        valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerActionPerformed(evt);
            }
        });

        annuler.setText("Annuler");
        annuler.setName("annuler");
        annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerActionPerformed(evt);
            }
        });

        jLabel12.setText("Email");
        jLabel12.setName("jLabel12");

        jLabel13.setText("Téléphone");
        jLabel13.setName("jLabel13");

        email.setName("email");

        telephone.setName("telephone");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(h_debut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(m_debut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(h_fin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(m_fin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel13)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(telephone)
                                            .addGap(78, 78, 78))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel1)
                                                        .addComponent(jLabel12))
                                                    .addGap(30, 30, 30))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(jLabel2)
                                                    .addGap(18, 18, 18)))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(prenom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                                    .addComponent(nom, javax.swing.GroupLayout.Alignment.LEADING)))))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(recurrence))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(periode, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ajout_dispo)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(annuler)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valider)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(telephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(h_debut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(m_debut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(h_fin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m_fin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(recurrence)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(periode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ajout_dispo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(annuler)
                    .addComponent(valider))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void refresh(){
    this.prenom.setText("");
    this.nom.setText("");
    this.email.setText("");
    this.telephone.setText("");
    this.periode.setText("jj/mm/aaaa");
    this.date.setText("");
    this.recurrence.setSelected(false);
    this.donner.desactive_sup_modif();
    this.intervenant = null;
    this.donner.refreshIntervenant();
}
 public ArrayList<String> list_Date(ArrayList<Creneau_Intervenant> liste_CI){
     ArrayList<String> list_Date = new ArrayList();
     for (Creneau_Intervenant l : liste_CI) {
            list_Date.add(afficherDate(l.getTsDebut()));
        }
     return list_Date;
}
 public ArrayList<String> list_Heure_Debut(ArrayList<Creneau_Intervenant> liste_CI){
     ArrayList<String> list_Heure_Debut = new ArrayList();
     for (Creneau_Intervenant l : liste_CI) {
            list_Heure_Debut.add(afficherHeure(l.getTsDebut()));
        }
     return list_Heure_Debut;
}
 public ArrayList<String> list_Heure_Fin(ArrayList<Creneau_Intervenant> liste_CI){
     ArrayList<String> list_Heure_Fin = new ArrayList();
     for (Creneau_Intervenant l : liste_CI) {
            list_Heure_Fin.add(afficherHeure(l.getTsFin()));
        }
     return list_Heure_Fin;
 }
private void refreshRecurence(){
    
    this.date.setText("jj/mm/aaaa");
    this.periode.setText("");
    this.recurrence.setSelected(false);
//    this.donner.desactive_sup_modif();
  //  this.donner.refreshIntervenant();
  //  this.jTable1.doLayout();
    DefaultTableModel modell = new DefaultTableModel(
            new Object [4][5] ,
            new String [] {});	
    this.jTable2.setModel(modell);
    try {
        this.list_creneauInter = Creneau_Intervenant.liste_Creneau_Intervenant(this.intervenant.getId());
    } catch (SQLException ex) {
        Logger.getLogger(Donner.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    ArrayList<String> listeDate = list_Date(this.list_creneauInter); 
    modell.addColumn("Date", listeDate.toArray()); 
    System.out.println(listeDate);
    ArrayList<String> listeheuredebut = list_Heure_Debut(this.list_creneauInter); 
    modell.addColumn("Heure Début", listeheuredebut.toArray()); 
    System.out.println(listeheuredebut);
    ArrayList<String> listheureFin = list_Heure_Fin(this.list_creneauInter); 
    modell.addColumn("Heure Fin", listheureFin.toArray()); 
    System.out.println(listheureFin);
}
private void creer(){
        this.intervenant.setNom(this.nom.getText());
        this.intervenant.setPrenom(this.prenom.getText());
        this.intervenant.setTelephone(this.telephone.getText());
        this.intervenant.setEmail(this.email.getText());
}
public String afficherHeure(Timestamp tim){
    String date = String.valueOf(tim);
    int h = Integer.parseInt(date.substring(11,13));
    int min = Integer.parseInt(date.substring(14, 16));
    return h+" h "+min;
}
public String afficherDate(Timestamp tim){
    String date = String.valueOf(tim);
    int an = Integer.parseInt(date.substring(0, 4));
    int mois = Integer.parseInt(date.substring(5, 7));
    int jour = Integer.parseInt(date.substring(8, 10));
    return jour+"/"+mois+"/"+an;
}
private Timestamp afficherTimestamp(String date,int heure, int minute, int recu){
        int an = Integer.parseInt(date.substring(6, 10));
        int mois = Integer.parseInt(date.substring(3, 5));
        int jour = Integer.parseInt(date.substring(0, 2));
        Timestamp ts = new Timestamp(an-1900,mois-1,jour+recu,heure,minute,0,0);
        return ts;
}
    private void ajout_dispoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajout_dispoActionPerformed
        // TODO add your handling code here:
        int n;
        switch(etat){
            case Intervenant:
                this.intervenant = new Intervenant(this.nom.getText(),this.prenom.getText(),this.email.getText(),this.telephone.getText(),true,true);
                this.intervenant.save();
                n = 1;
                if(this.recurrence.isSelected()){
                    n = Integer.parseInt(this.periode.getText());
                }
                for(int i = 0;i< n; i++){
                    this.creneauInt = new Creneau_Intervenant(
                            this.intervenant.getId(),
                            afficherTimestamp(this.date.getText(), Integer.parseInt(this.h_debut.getSelectedItem().toString()), Integer.parseInt(this.m_debut.getSelectedItem().toString()), i*7),
                            afficherTimestamp(this.date.getText(), Integer.parseInt(this.h_fin.getSelectedItem().toString()), Integer.parseInt(this.m_fin.getSelectedItem().toString()), i*7));
                    this.creneauInt.save();
                }
                refreshRecurence();
                this.etat = Etat.Intervenant1;
                break;
            case Intervenant1:
                n = 1;
                if(this.recurrence.isSelected()){
                    n = Integer.parseInt(this.periode.getText());
                }
                for(int i = 0;i< n; i++){
                    this.creneauInt = new Creneau_Intervenant(
                            this.intervenant.getId(),
                            afficherTimestamp(this.date.getText(), Integer.parseInt(this.h_debut.getSelectedItem().toString()), Integer.parseInt(this.m_debut.getSelectedItem().toString()), i*7),
                            afficherTimestamp(this.date.getText(), Integer.parseInt(this.h_fin.getSelectedItem().toString()), Integer.parseInt(this.m_fin.getSelectedItem().toString()), i*7));
                    this.creneauInt.save();
                }
                refreshRecurence();
                this.etat = Etat.Intervenant1;
                break;
                
        }
    }//GEN-LAST:event_ajout_dispoActionPerformed

    private void annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerActionPerformed
        // TODO add your handling code here:
        switch(etat){
            case Intervenant:
                this.dispose();
                this.donner.desactive_sup_modif();
                break;
            case Intervenant1:
                this.dispose();
                this.donner.desactive_sup_modif();
                break;
                
        }
    }//GEN-LAST:event_annulerActionPerformed

    private void validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerActionPerformed
        // TODO add your handling code here:
        switch(etat){
            case Intervenant:
                this.intervenant = new Intervenant(this.nom.getText(),this.prenom.getText(),this.email.getText(),this.telephone.getText(),true,true);
                this.intervenant.save();
                refresh();
                etat = Etat.Intervenant;
                break;
            case Intervenant1:
                creer();
                this.intervenant.save();
                refresh();
                this.dispose();
                break;
                
        }
    }//GEN-LAST:event_validerActionPerformed

    private void h_debutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h_debutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_h_debutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(New_Intervenant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(New_Intervenant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(New_Intervenant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(New_Intervenant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                New_Intervenant dialog = new New_Intervenant(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajout_dispo;
    private javax.swing.JButton annuler;
    private javax.swing.JTextField date;
    private javax.swing.JTextField email;
    private javax.swing.JComboBox h_debut;
    private javax.swing.JComboBox h_fin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JComboBox m_debut;
    private javax.swing.JComboBox m_fin;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField periode;
    private javax.swing.JTextField prenom;
    private javax.swing.JCheckBox recurrence;
    private javax.swing.JTextField telephone;
    private javax.swing.JButton valider;
    // End of variables declaration//GEN-END:variables

    private enum Etat{
        Intervenant,
        Intervenant1
    }
    private Etat etat;
    public void init(String n,int id){
        if(n.equals("Intervenant"))
            etat = Etat.Intervenant;
        else if (n.equals("Intervenant1")){
            etat = Etat.Intervenant1;
            try {
                this.intervenant = new Intervenant(id);
            } catch (SQLException ex) {
                Logger.getLogger(New_Etudiant.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.nom.setText(intervenant.getNom());
            this.prenom.setText(intervenant.getPrenom());
            this.email.setText(intervenant.getEmail());
            this.telephone.setText(intervenant.getTelephone());
            refreshRecurence();
        }
    }
}
