/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edt.Frame;

import edt.Classe.Intervenant;
import edt.Classe.Salle;
import edt.Classe.Seance;
import edt.Classe.UE;
import edt.mysql.BD_MySQL;
import edt.view.Donner;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Marie
 */
public class New_Seance extends javax.swing.JDialog {
    private Donner donner;
    private Seance creneau;
    private int id_promo;

    /**
     * Creates new form New_Seance
     */
    public New_Seance(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public New_Seance(java.awt.Frame parent,String titre, boolean modal,Donner donner, String etat, int id, int id_promo) {
        super(parent,titre, modal);
        initComponents();
        this.id_promo = id_promo;
        init(etat,id);
        this.donner = donner;
        this.setLocation( Toolkit.getDefaultToolkit().getScreenSize().width/2-this.getWidth()/2,Toolkit.getDefaultToolkit().getScreenSize().height/2-this.getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        cours = new javax.swing.JRadioButton();
        tp = new javax.swing.JRadioButton();
        td = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ue = new javax.swing.JComboBox();
        nom = new javax.swing.JTextField();
        intervenant = new javax.swing.JComboBox();
        salle = new javax.swing.JComboBox();
        duree = new javax.swing.JTextField();
        cours_prec = new javax.swing.JComboBox();
        valider = new javax.swing.JButton();
        annuler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cours.setText("Cours");

        tp.setText("TP");

        td.setText("TD");

        jLabel1.setText("UE");

        jLabel2.setText("Nom");

        jLabel3.setText("Intervenant");

        jLabel4.setText("Salle");

        jLabel5.setText("Durée");

        jLabel6.setText("Cours précédent");

        ue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ueActionPerformed(evt);
            }
        });

        cours_prec.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "......" }));

        valider.setText("Valider");
        valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerActionPerformed(evt);
            }
        });

        annuler.setText("Annuler");
        annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cours_prec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cours)
                        .addGap(18, 18, 18)
                        .addComponent(tp)
                        .addGap(18, 18, 18)
                        .addComponent(td))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(intervenant, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(salle, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(duree, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(nom, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ue, javax.swing.GroupLayout.Alignment.LEADING, 0, 86, Short.MAX_VALUE)))))
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(annuler)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valider)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cours)
                    .addComponent(tp)
                    .addComponent(td))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(intervenant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(salle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(duree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cours_prec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valider)
                    .addComponent(annuler))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void refresh(){
    this.nom.setText("");
    this.duree.setText("");
    desactiveGoupeBouton();
    this.donner.desactive_sup_modif();
    this.creneau = null;
    this.donner.refreshSeance();
    }
    private void desactiveGoupeBouton(){
        this.cours.setSelected(false);
        this.tp.setSelected(false);
        this.td.setSelected(false);
    }
    private void creer(){
            this.creneau.setNom(this.nom.getText());
    }
    
    private int typeCour(){
        if(this.cours.isSelected())
            return 1;
        else if(this.tp.isSelected())
            return 3;
        else if(this.td.isSelected())
            return 2;
        return 0;
    }
    private int idSalle(){
        return Salle.id_Salle(
                this.salle.getSelectedItem().toString().substring(this.salle.getSelectedItem().toString().lastIndexOf(" ")+1, this.salle.getSelectedItem().toString().length()),
                this.salle.getSelectedItem().toString().substring(0, this.salle.getSelectedItem().toString().lastIndexOf(" ")));
    }
    private int idIntervenant(){
        return Intervenant.id_Intervenant(
                this.intervenant.getSelectedItem().toString().substring(0, this.intervenant.getSelectedItem().toString().lastIndexOf(" ")),
                this.intervenant.getSelectedItem().toString().substring(this.intervenant.getSelectedItem().toString().lastIndexOf(" ")+1, this.intervenant.getSelectedItem().toString().length()));
    }
    private int idUE(){
        return UE.id_UE_promotion(this.ue.getSelectedItem().toString(), this.id_promo);
    }
    private int idPrec(){
        return Seance.id_Creneau(this.cours_prec.getSelectedItem().toString());
    }
    private void validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerActionPerformed
        // TODO add your handling code here:
        switch(etat){
            case Creneau:
                this.creneau = new Seance(this.nom.getText(),Integer.parseInt(this.duree.getText()),typeCour(),idSalle(),idIntervenant(),idUE(),idPrec());
                this.creneau.save();
                refresh();
                etat = Etat.Creneau;
                break;
            case Creneau1:
                creer();
                this.creneau.save();
                refresh();
                this.dispose();
                break;
                
        }
    }//GEN-LAST:event_validerActionPerformed

    private void annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerActionPerformed
        // TODO add your handling code here:
        switch(etat){
            case Creneau:
                this.dispose();
                this.donner.desactive_sup_modif();
                break;
            case Creneau1:
                this.dispose();
                this.donner.desactive_sup_modif();
                break;
                
        }
    }//GEN-LAST:event_annulerActionPerformed

    private void ueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ueActionPerformed
        // TODO add your handling code here:
        this.cours_prec.removeAllItems();
        this.cours_prec.addItem(".....");
        for(String nomSeance : Seance.liste_nom_Seance_UE(idUE())){
           this.cours_prec.addItem(nomSeance);
           System.out.println("coucouc");
        }
    }//GEN-LAST:event_ueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(New_Seance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(New_Seance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(New_Seance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(New_Seance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                New_Seance dialog = new New_Seance(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annuler;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JRadioButton cours;
    private javax.swing.JComboBox cours_prec;
    private javax.swing.JTextField duree;
    private javax.swing.JComboBox intervenant;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nom;
    private javax.swing.JComboBox salle;
    private javax.swing.JRadioButton td;
    private javax.swing.JRadioButton tp;
    private javax.swing.JComboBox ue;
    private javax.swing.JButton valider;
    // End of variables declaration//GEN-END:variables
    private enum Etat{
        Creneau,
        Creneau1
    }
    private Etat etat;
    public void init(String n,int id){
        if(n.equals("Creneau"))
            etat = Etat.Creneau;
        else if (n.equals("Creneau1")){
            etat = Etat.Creneau1;
            try {
                this.creneau = new Seance(id);
            } catch (SQLException ex) {
                Logger.getLogger(New_Etudiant.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.nom.setText(creneau.getNom());
        }
         for(String nomUE : UE.list_nom_UE(this.id_promo)){
           this.ue.addItem(nomUE);
        }
         for(String nomIntervenant : Intervenant.list_nom_Intervenant()){
           this.intervenant.addItem(nomIntervenant);
        }
         for(String nomSalle : Salle.list_nom_Salle()){
           this.salle.addItem(nomSalle);
        }
    }
    
}
