/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewPromotion.java
 *
 * Created on 2 avr. 2012, 15:58:51
 */
package edt.Frame;

import edt.Classe.Promotion;
import edt.mysql.BD_MySQL;
import edt.view.Donner;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Marie
 */
public class NewPromotion extends javax.swing.JDialog {
    private Promotion promo;
    private Donner donner;
    /** Creates new form NewPromotion */
    public NewPromotion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocation( Toolkit.getDefaultToolkit().getScreenSize().width/2-this.getWidth()/2,Toolkit.getDefaultToolkit().getScreenSize().height/2-this.getHeight()/2);
    
    }
    public NewPromotion(java.awt.Frame parent, String titre, boolean modal) {
        super(parent, titre, modal);
        initComponents();
        this.setLocation( Toolkit.getDefaultToolkit().getScreenSize().width/2-this.getWidth()/2,Toolkit.getDefaultToolkit().getScreenSize().height/2-this.getHeight()/2);
    
    }
    public NewPromotion(java.awt.Frame parent, String titre, boolean modal,Donner donner, String etat, int id) {
        super(parent, titre, modal);
        initComponents();
        init(etat,id);
        this.donner = donner;
        this.setLocation( Toolkit.getDefaultToolkit().getScreenSize().width/2-this.getWidth()/2,Toolkit.getDefaultToolkit().getScreenSize().height/2-this.getHeight()/2);
    
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        iLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        annee = new javax.swing.JTextField();
        d_debut = new javax.swing.JTextField();
        d_fin = new javax.swing.JTextField();
        valider = new javax.swing.JButton();
        annuler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nom");
        jLabel1.setName("jLabel1"); // NOI18N

        iLabel2.setText("Année");
        iLabel2.setName("iLabel2"); // NOI18N

        jLabel3.setText("Date de début");
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText("Date de fin");
        jLabel4.setName("jLabel4"); // NOI18N

        nom.setName("nom"); // NOI18N

        annee.setName("annee"); // NOI18N

        d_debut.setText("jj/mm/aaaa");
        d_debut.setName("d_debut"); // NOI18N

        d_fin.setText("jj/mm/aaaa");
        d_fin.setName("d_fin"); // NOI18N

        valider.setText("Valider");
        valider.setName("valider"); // NOI18N
        valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerActionPerformed(evt);
            }
        });

        annuler.setText("Annuler");
        annuler.setName("annuler"); // NOI18N
        annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(iLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(d_fin)
                            .addComponent(d_debut, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                            .addComponent(annee)
                            .addComponent(nom, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(annuler)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valider)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(annee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d_debut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d_fin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valider)
                    .addComponent(annuler))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void refresh(){
    this.nom.setText("");
    this.annee.setText("");
    this.d_debut.setText("jj/mm/aaaa");
    this.d_fin.setText("jj/mm/aaaa");
    this.donner.desactive_sup_modif();
    this.promo = null;
    this.donner.refreshPromotion();
}
private void creer(){
        this.promo.setNom(this.nom.getText());
        this.promo.setAnnee(Integer.parseInt(this.annee.getText()));
        this.promo.setTsDebut(afficherTimestamp(this.d_debut.getText()));
        this.promo.setTsFin(afficherTimestamp(this.d_fin.getText()));
}  
private Timestamp afficherTimestamp(String date){
        int an = Integer.parseInt(date.substring(6, 10));
        int mois = Integer.parseInt(date.substring(3, 5));
        int jour = Integer.parseInt(date.substring(0, 2));
        Timestamp ts = new Timestamp(an-1900,mois-1,jour,0,0,0,0);
        return ts;
}
    private void validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerActionPerformed
        // TODO add your handling code here:
        
        BD_MySQL.init();
        switch(etat){
            case Promotion:
                this.promo = new Promotion(this.nom.getText(), Integer.parseInt(this.annee.getText()), afficherTimestamp(this.d_debut.getText()), afficherTimestamp(this.d_fin.getText()));
                this.promo.save();
                refresh();
                etat = Etat.Promotion;
                break;
            case Promotion1:
                creer();
                this.promo.save();
                refresh();
                this.dispose();
                break;
            case Promotion2:
                this.promo = new Promotion(this.nom.getText(), Integer.parseInt(this.annee.getText()), afficherTimestamp(this.d_debut.getText()), afficherTimestamp(this.d_fin.getText()));
                this.promo.save();
                refresh();
                this.dispose();
                break;
                
        }
    }//GEN-LAST:event_validerActionPerformed

    private void annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerActionPerformed
        // TODO add your handling code here:
        switch(etat){
            case Promotion:
                this.dispose();
                this.donner.desactive_sup_modif();
                break;
            case Promotion1:
                this.dispose();
                this.donner.desactive_sup_modif();
                break;
            case Promotion2:
                this.dispose();
                this.donner.desactive_sup_modif();
                break;
                
        }
    }//GEN-LAST:event_annulerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewPromotion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewPromotion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewPromotion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewPromotion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                NewPromotion dialog = new NewPromotion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField annee;
    private javax.swing.JButton annuler;
    private javax.swing.JTextField d_debut;
    private javax.swing.JTextField d_fin;
    private javax.swing.JLabel iLabel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nom;
    private javax.swing.JButton valider;
    // End of variables declaration//GEN-END:variables
    private enum Etat{
        Promotion,
        Promotion1,
        Promotion2
    }
    private Etat etat;
    public String afficherDate(Timestamp tim){
        String date = String.valueOf(tim);
        int an = Integer.parseInt(date.substring(0, 4));
        int mois = Integer.parseInt(date.substring(5, 7));
        int jour = Integer.parseInt(date.substring(8, 10));
        return jour+"/"+mois+"/"+an;
    }
    public void init(String n,int id){
        if(n.equals("Promotion"))
            etat = Etat.Promotion;
        else if (n.equals("Promotion2")){
            etat = Etat.Promotion2;            
        }
        else if (n.equals("Promotion1")){
            etat = Etat.Promotion1;
            try {
                this.promo = new Promotion(id);
            } catch (SQLException ex) {
                Logger.getLogger(New_Etudiant.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.nom.setText(this.promo.getNom());
            this.annee.setText(String.valueOf(this.promo.getAnnee()));
            this.d_debut.setText(afficherDate(this.promo.getTsDebut()));
            this.d_fin.setText(afficherDate(this.promo.getTsFin()));
        }
    }
}
